changer <user.homophones_canonical>: user.homophones_show(homophones_canonical)
changer that: user.homophones_show_selection()
changer force <user.homophones_canonical>: user.homophones_force_show(homophones_canonical)
changer force: user.homophones_force_show_selection()
changer hide: user.homophones_hide()
